name: ezbooking
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3-130.0.dev

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  lottie: ^3.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  animated_bottom_navigation_bar: ^1.3.3
  sticky_headers: ^0.3.0+2
  intl:
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  dio: ^5.7.0
  get_it: ^8.0.0
  flutter_secure_storage: ^9.2.2
  syncfusion_flutter_datepicker: ^27.1.55
  freezed: ^2.5.7
  build_runner: ^2.4.13
  firebase_ui_firestore: ^1.7.0
  shimmer: ^3.0.0
  package_info_plus: ^8.1.0
  photo_view: ^0.15.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  webview_flutter: ^4.10.0
  flutter_rating_bar: ^4.0.1
  timeago: ^3.7.0
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  encrypt: ^5.0.3
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  external_path: ^2.0.1
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6

#  vnpay_flutter: ^1.0.3
dependency_overrides:
  http: ^0.13.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

